name: Deploy

on:
    workflow_dispatch:

env:
    GIT_CONFIG_NAME: github-actions
    GIT_CONFIG_EMAIL: yukino-org@users.noreply.github.com
    GIT_COMMIT_MSG: "[actions] deploy (${{ github.sha }})"
    GIT_OUTPUT_DIR: dist
    GIT_OUTPUT_BRANCH: dist

jobs:
    deploy-store:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: dart pub get

            - name: 🔨 Build store
              run: dart run ./store/build.dart

            - name: 🚀 Deploy
              uses: zyrouge/github-push-action@v1
              with:
                  local-username: ${{ env.GIT_CONFIG_NAME }}
                  local-email: ${{ env.GIT_CONFIG_EMAIL }}
                  commit-message: ${{ env.GIT_COMMIT_MSG }}
                  directory: ${{ env.GIT_OUTPUT_DIR }}
                  branch: ${{ env.GIT_OUTPUT_BRANCH }}
                  skip-fetch: true
                  force: true
