name: Test Modules

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

env:
    GIT_CONFIG_NAME: "github-actions"
    GIT_CONFIG_EMAIL: yukino-org@users.noreply.github.com
    GIT_COMMIT_MSG: "[actions] test-modules (${{ github.sha }})"
    GIT_OUTPUT_DIR: dist-summary
    GIT_OUTPUT_BRANCH: summary

jobs:
    test-modules:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: dart pub get

            - name: 🧪 Test modules
              run: dart run ./store/test.dart --ci

            - name: 🚀 Upload summary
              uses: zyrouge/github-push-action@v1
              with:
                  local-username: ${{ env.GIT_CONFIG_NAME }}
                  local-email: ${{ env.GIT_CONFIG_EMAIL }}
                  commit-message: ${{ env.GIT_COMMIT_MSG }}
                  directory: ${{ env.GIT_OUTPUT_DIR }}
                  branch: ${{ env.GIT_OUTPUT_BRANCH }}
                  skip-fetch: true
                  checkout-orphan: true
                  force: true
